### ISSUE TITLE
2021-12-17 Peer-to-peer code review

### ISSUE THREAD

**Issue by vechicin** [Mre55/Leaderboard#4]
# Excellent Job Mre! 💯 🔥 👍 
Your code is very clean, efficient, and readable. I also enjoyed your page's style a lot, it looked very nice and welcoming.

The only suggestion I have is, consider creating a separate JavaScript file for your API functions. Using modules was actually part of the project requirements so definitely consider using modules for this and future projects.

## Once again, fantastic job, keep it up! 🥇 💪 ✅ 🤓

**Comment by ShadyShawkat** [comment]
# Fantastic Job @Mre55! 🔥 💯 

Your code is very clean. I also enjoyed how you documented your code, it looked very nice.

I don't have anything considering changes in your code, I think it's really well written.

### Excellent job, keep it up!  💪 🤓 ✅

**Comment by Mre55** [comment]
Thank you @vechicin and @ShadyShawkat for your appreciation and insight I really appreciate and also I address your insight.
